In [169]:
import numpy as np
import pandas as pd

#### 1. Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная). Произвести расчет как с использованием intercept, так и без.

In [170]:
X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])

In [171]:
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

#### 1.1 Без intercept (a =0)

$W = (X \cdot X^T)^{-1} \cdot X \cdot y^T $

In [172]:
X1 = X.reshape(1,10)
X1

array([[ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110]])

In [173]:
y = y.reshape(1,10)
y

array([[401, 574, 874, 919, 459, 739, 653, 902, 746, 832]])

In [174]:
b1 = np.linalg.inv(X1 @ X1.T) @ X1 @ y.T
b1[0,0]

5.889820420132689

#### 1.2 С учетом intercept (a !=0)

In [175]:
ones= np.ones((1,10))

In [176]:
X2 = X.reshape(1,10)
X2 = np.vstack([ones,X2])
X2

array([[  1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.],
       [ 35.,  45., 190., 200.,  40.,  70.,  54., 150., 120., 110.]])

In [177]:
W = np.linalg.inv(X2 @ X2.T) @ X2 @ y.T

In [178]:
a = W[0,0]
a

444.17735732435915

In [179]:
b2 = W[1,0]
b2

2.6205388824027684

#### 1.3 C учетом intercept без использования матриц

In [180]:
b = (np.mean(X*y) - np.mean(X)*np.mean(y))/ (np.mean(X**2) - np.mean(X)**2)
b

2.620538882402765

In [181]:
a = np.mean(y) - b*np.mean(X)
a

444.1773573243596

#### 2.Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (без intercept).

In [182]:
n = 10

In [183]:
alpha = 1e-6

In [184]:
w1 = 0.1

In [185]:
f_p = (2/n) * np.sum((w1*X - y) * X)

In [186]:
for i in range(1000):
    w1 -= alpha * (2/n) * np.sum((w1*X - y) * X)

In [187]:
w1

5.889820420128437

Значение коэффициента до 10-го знака совпадает со значением,найденным в задании 1.1

#### 3.В каких случаях для вычисления доверительных интервалов и проверки статистических гипотез используется таблица значений функции Лапласа, а в каких - таблица критических точек распределения Стьюдента?

Если неизвестна дисперсия генеральной совокупности и количество значений в выборке не велико (120 и меньше, а чаще всего 20-30),то следует использовать таблицу Стьюдента, а для расчетов среднеквадратичного отклонения использовать формулу несмещенного отклонения. В остальных случаях нужно использовать таблицы значений функции Лапласса.  

#### *4. Произвести вычисления как в пункте 2, но с вычислением intercept. Учесть, что изменение коэффициентов должно производиться на каждом шаге одновременно (то есть изменение одного коэффициента не должно влиять на изменение другого во время одной итерации).